### ISSUE TITLE
When is the code open

### ISSUE THREAD

**Issue by DL-ljw** [szq0214/GRP-DSOD#1]
sorry for bothering you, can you tell me when the code open to public? Thank you very much for your work. It's a great help to me

**Comment by szq0214** [comment]
Hi @DL-ljw, thanks for your interests. We will release the code ASAP (maybe within this month).

**Comment by DL-ljw** [comment]
Thank you so much!

**Comment by zt706** [comment]
Thank you!

**Comment by amiltonwong** [comment]
Hi, authors,
When will the code be released?

THX!

**Comment by shridharkini6** [comment]
Hi,
When will be the code open?
Thankx

**Comment by szq0214** [comment]
Hi @DL-ljw, @zt706, @amiltonwong and @shridharkini6,

Sorry for the late reply! 

We have merged the GRP_DSOD code in DSOD repository (https://github.com/szq0214/DSOD). Please check out there.

In this repository, we are planning to release a pytorch version of DSOD and GRP_DSOD. Please stay tuned!

We appreciate your interest in our work and thank you all very much!

**Comment by DL-ljw** [comment]
Hi @szq0214,
Thank you soooooooooo much.
